const PDFDocument = require('pdfkit');
const ReviewCase = require('../models/ReviewCase');

/**
 * 🤖 IMPROVED AI ANALYSIS PDF
 */
exports.getAIAnalysisPDF = async (req, res) => {
    try {
        const { caseId } = req.params;
        const caseData = await ReviewCase.findById(caseId);

        if (!caseData) return res.status(404).json({ success: false, message: 'Case not found.' });

        // Standard US Letter is 612 x 792 points
        const doc = new PDFDocument({ size: 'LETTER', margin: 0 }); 

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `inline; filename=AI_Analysis_${caseId}.pdf`);
        doc.pipe(res);

        // 1. TOP BANNER
        doc.rect(0, 0, 612, 80).fill('#F0F9F8'); // Light teal background
        doc.fillColor('#1E7D75').font('Helvetica-Bold').fontSize(22).text('Praman AI', 50, 30);
        doc.fillColor('#64748B').font('Helvetica').fontSize(10).text('PRELIMINARY CONTEXT REPORT', 50, 55);

        // 2. CASE INFO STRIP
        doc.rect(0, 80, 612, 40).fill('#1E7D75');
        doc.fillColor('#FFFFFF').fontSize(10).text(`CASE ID: ${caseId.toUpperCase()}`, 50, 95);
        doc.text(`DATE: ${new Date().toLocaleDateString()}`, 450, 95);

        // 3. CONTENT SECTION
        let currentY = 140;

        // Risk Level Badge
        const riskColor = caseData.aiAnalysis?.riskLevel?.toLowerCase() === 'high' ? '#E11D48' : '#1E7D75';
        doc.fillColor(riskColor).font('Helvetica-Bold').fontSize(12).text(`RISK ASSESSMENT: ${caseData.aiAnalysis?.riskLevel || 'NOT RATED'}`, 50, currentY);
        
        currentY += 30;
        doc.moveTo(50, currentY).lineTo(562, currentY).strokeColor('#E2E8F0').lineWidth(1).stroke();
        
        currentY += 20;
        doc.fillColor('#1E7D75').font('Helvetica-Bold').fontSize(14).text('AI Executive Summary', 50, currentY);
        
        currentY += 25;
        doc.fillColor('#334155').font('Helvetica').fontSize(11).text(
            caseData.aiAnalysis?.summary || "Analysis in progress.", 
            50, currentY, { width: 512, align: 'justify', lineGap: 4 }
        );

        // 4. FOOTER DISCLAIMER
        doc.fontSize(8).fillColor('#94A3B8').text(
            'DISCLAIMER: This report is generated by AI for clinical context. It is not a final diagnosis. Please refer to the Specialist Verdict.',
            50, 740, { width: 512, align: 'center' }
        );

        doc.end();
    } catch (err) {
        console.error(err);
        res.status(500).send('Error');
    }
};

/**
 * 👨‍⚕️ IMPROVED DOCTOR REVIEW PDF
 */
exports.getDoctorReviewPDF = async (req, res) => {
    try {
        const { caseId } = req.params;
        const reviewData = await ReviewCase.findById(caseId).populate('doctorId', 'name');

        if (!reviewData || reviewData.status !== 'COMPLETED') {
            return res.status(400).json({ success: false, message: 'Review not finalized.' });
        }

        const doc = new PDFDocument({ size: 'LETTER', margin: 50 });

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', `inline; filename=Specialist_Verdict_${caseId}.pdf`);
        doc.pipe(res);

        // 1. PROFESSIONAL LETTERHEAD
        doc.fillColor('#1E7D75').font('Helvetica-Bold').fontSize(26).text('Praman AI', { align: 'right' });
        doc.fontSize(10).fillColor('#64748B').text('Clinical Consultation Services', { align: 'right' });
        
        doc.moveDown(1);
        doc.moveTo(50, doc.y).lineTo(562, doc.y).strokeColor('#1E7D75').lineWidth(2).stroke();
        doc.moveDown(2);

        // 2. DOCTOR & CASE DETAILS
        doc.fillColor('#64748B').font('Helvetica').fontSize(10).text('REVIEWING SPECIALIST');
        doc.fillColor('#1E293B').font('Helvetica-Bold').fontSize(12).text(`Dr. ${reviewData.doctorId?.name || 'Medical Specialist'}`);
        
        doc.moveDown(1);
        doc.fillColor('#64748B').font('Helvetica').fontSize(10).text('CASE REFERENCE');
        doc.fillColor('#1E293B').font('Helvetica-Bold').fontSize(12).text(caseId.toUpperCase());

        doc.moveDown(2);

        // 3. FINAL VERDICT BOX
        doc.rect(50, doc.y, 512, 80).fill('#F8FAFC'); // Light gray box
        doc.fillColor('#1E7D75').font('Helvetica-Bold').fontSize(14).text('FINAL CLINICAL VERDICT', 65, doc.y - 70);
        doc.moveDown(0.5);
        doc.fillColor('#1E293B').font('Helvetica').fontSize(12).text(
            reviewData.doctorOpinion?.finalVerdict || "No verdict recorded.",
            { width: 480 }
        );

        doc.moveDown(4);

        // 4. RECOMMENDATIONS
        doc.fillColor('#1E7D75').font('Helvetica-Bold').fontSize(14).text('RECOMMENDATIONS & NEXT STEPS');
        doc.moveDown(0.5);
        doc.fillColor('#334155').font('Helvetica').fontSize(11).text(
            reviewData.doctorOpinion?.recommendations || "Follow standard protocols.",
            { width: 512, lineGap: 5 }
        );

        // 5. SIGNATURE LINE
        const bottomY = 680;
        doc.moveTo(350, bottomY).lineTo(550, bottomY).strokeColor('#CBD5E1').lineWidth(1).stroke();
        doc.fontSize(9).fillColor('#64748B').text('Digitally Signed by Medical Specialist', 350, bottomY + 5, { width: 200, align: 'center' });
        doc.text(`Verification Date: ${new Date().toLocaleDateString()}`, 350, bottomY + 18, { width: 200, align: 'center' });

        doc.end();
    } catch (err) {
        console.error(err);
        res.status(500).send('Error');
    }
};

module.exports = {
    getAIAnalysisPDF: exports.getAIAnalysisPDF,
    getDoctorReviewPDF: exports.getDoctorReviewPDF
};